repository:
  path: github.com/fgouteroux/alertmanager-silences-exporter
build:
  binaries:
    - name: alertmanager-silences-exporter
  flags: -a -tags 'netgo static_build'
  ldflags: |
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  files:
    - LICENSE
    - README.md
crossbuild:
  platforms:
    - linux/amd64
    - linux/386
    - linux/arm
    - linux/arm64
    - darwin/amd64
    - darwin/386

