#!/bin/sh
set -ex

apt-get update
apt-get install --yes \
  ca-certificates \
  curl

# Install alertmanager-silences-exporter
useradd -r -d /opt/alertmanager-silences-exporter ase

mkdir -p /opt/alertmanager-silences-exporter
mv /alertmanager-silences-exporter /opt/alertmanager-silences-exporter

chown -R ase /opt/alertmanager-silences-exporter

# Clean
apt-get remove --purge curl --yes
apt-get autoremove --purge --yes
apt-get clean --yes

# CIS Benchmarking
sed -i 's/^PASS_MAX_DAYS.*$/PASS_MAX_DAYS   60/g' /etc/login.defs
sed -i 's/^PASS_MIN_DAYS.*$/PASS_MIN_DAYS   7/g' /etc/login.defs
sed -i 's/^UMASK.*$/UMASK   027/g' /etc/login.defs
